name: Lint and Format

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm
        working-directory: ./packages/contracts

      - name: Install dependencies
        run: pnpm install
        working-directory: ./packages/contracts

      - name: Run lint
        run: pnpm run lint
        working-directory: ./packages/contracts
